site_name: "turnierplan.NET Documentation"
site_author: "turnierplan.NET"
docs_dir: "pages"
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
  navigation_depth: 4
  locale: en
extra_css:
  - "assets/turnierplan.css"
markdown_extensions:
  - admonition:
