site_name: "turnierplan.NET"
site_author: "turnierplan.NET"
site_url: "https://docs.turnierplan.net"
site_description: "The administrator and user documentation for turnierplan.NET"

repo_url: "https://github.com/turnierplan-NET/turnierplan.NET"
edit_uri: "blob/main/docs/pages/"

copyright: "Copyright &copy; 2026 Elias HÃ¶rner"

docs_dir: "pages"

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
  navigation_depth: 4
  locale: en

nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - About:
      - Releases: "https://github.com/turnierplan-NET/turnierplan.NET/releases"
      - License: "https://github.com/turnierplan-NET/turnierplan.NET/blob/main/LICENSE"

extra_css:
  - "assets/turnierplan.css"

markdown_extensions:
  - admonition:
