on:
  push:
    branches:
      - main
      - eliaspr/new-docs # TODO: Remove this line!
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
    types: [opened, synchronize, reopened]

jobs:
  documentation:
    name: "Documentation"
    runs-on: ubuntu-24.04
    steps:
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: "Build documentation"
        run: "python3 -m mkdocs build"
        working-directory: "docs"
